apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}-service
spec:
  ports:
  - port: 80
    name: {{ template "chart.fullname" . }}
  selector:
    app: {{ template "chart.fullname" . }}
  type: ClusterIP
