export type EditedEmployee = {
  fullName: string,
  corporateEmail: string,
  personalEmail: string | null,
  phone: string | null,
  gitHub: string | null,
  gitLab: string | null,
  ratePerHour: number | null,
  fullSalary: number | null,
  employmentType: number | null,
  parking: number | null,
  hireDate: Date | null,
  dismissalDate?: Date | null,
  isEmployedOfficially: boolean,
  isCurrentEmployee?: boolean,
  personnelNumber: string | null,
};

export type Employee = {
  employeeId: number,
  fullName: string,
  corporateEmail: string,
  personalEmail: string | null,
  phone: string | null,
  gitHub: string | null,
  gitLab: string | null,
  netSalary: number | null,
  ratePerHour: number | null,
  fullSalary: number | null,
  employmentType: number | null,
  parking: number | null,
  personnelNumber: string | null,
  hireDate: string | null,
  isCurrentEmployee: boolean,
  isBlankEmployee: boolean,
};
