export const mockData = [
  {
    employeeId: 1,
    fullName: `Ahris Smith`,
    corporateEmail: `csmith@tourmalinecore.com`,
    personalEmail: `csmith@mail.ru`,
    phone: `+79935836350`,
    gitHub: `@csmith`,
    gitLab: `@csmith`,
    netSalary: 10005.05,
    ratePerHour: 400,
    fullSalary: 20000,
    employmentType: 0.5,
    parking: 1800.5,
    personnelNumber: `01/20`,
    hireDate: `2023-03-02T06:04:43.960Z`,
    isCurrentEmployee: true,
    isBlankEmployee: false,
  },
  {
    employeeId: 3,
    fullName: `Cmdrey Yasnovsky`,
    corporateEmail: `csmith@tourmalinecore.com`,
    personalEmail: null,
    phone: null,
    gitHub: null,
    gitLab: null,
    netSalary: null,
    ratePerHour: null,
    fullSalary: null,
    employmentType: null,
    parking: null,
    personnelNumber: null,
    hireDate: null,
    isCurrentEmployee: true,
    isBlankEmployee: true,
  },
  {
    employeeId: 2,
    fullName: `Bndrey Yasnovsky`,
    corporateEmail: `csmith@tourmalinecore.com`,
    personalEmail: `csmith@mail.ru`,
    phone: `+79935836356`,
    gitHub: `@csmith`,
    gitLab: `@csmith`,
    netSalary: null,
    ratePerHour: 0,
    fullSalary: null,
    employmentType: 0.5,
    parking: 0,
    personnelNumber: `01/20`,
    hireDate: `2023-03-02T06:04:43.960Z`,
    isCurrentEmployee: false,
    isBlankEmployee: false,
  },
]
