export const mockData = [
  {
    employeeId: 1,
    fullName: 'Ahris Smith',
    corporateEmail: 'csmith@tourmalinecore.com',
    personalEmail: 'csmith@mail.ru',
    phone: '+7993583635',
    gitHub: '@csmith',
    gitLab: '@csmith',
    netSalary: 10005.05,
    ratePerHour: 400,
    fullSalary: 20000,
    employmentType: 0.5,
    parking: 1800.5,
    personnelNumber: '01/20',
    hireDate: '01.03.2020T09:00:05',
    isCurrentEmployee: true,
    isBlankEmployee: true,
  },
  {
    employeeId: 3,
    fullName: 'Cmdrey Yasnovsky',
    corporateEmail: 'csmith@tourmalinecore.com',
    personalEmail: 'csmith@mail.ru',
    phone: '+7993583635',
    gitHub: '@csmith',
    gitLab: '@csmith',
    netSalary: null,
    ratePerHour: 0,
    fullSalary: null,
    employmentType: 0.5,
    parking: 0,
    personnelNumber: '01/20',
    hireDate: '01.03.2020T09:00:05',
    isCurrentEmployee: false,
    isBlankEmployee: false,
  },
  {
    employeeId: 2,
    fullName: 'Bndrey Yasnovsky',
    corporateEmail: 'csmith@tourmalinecore.com',
    personalEmail: 'csmith@mail.ru',
    phone: '+7993583635',
    gitHub: '@csmith',
    gitLab: '@csmith',
    netSalary: null,
    ratePerHour: 0,
    fullSalary: null,
    employmentType: 0.5,
    parking: 0,
    personnelNumber: '01/20',
    hireDate: '01.03.2020T09:00:05',
    isCurrentEmployee: false,
    isBlankEmployee: false,
  },
];
