name: Component Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install-cypress:
    uses: ./.github/workflows/.reusable-install-cypress.yml
  
  component_test:
    runs-on: ubuntu-24.04 
    container: cypress/browsers:node-24.20.0-chrome-152.0.7977.64-1-ff-154.0.1-edge-151.0.4129.107-1
    strategy:
      fail-fast: false
    needs: install-cypress
    steps:
      - name: Checkout ui
        uses: actions/checkout@v7

      - name: Download the dist folders
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist

      - name: Cypress run component tests
        uses: cypress-io/github-action@v7
        with:
          component: true
          start: npm start
          browser: electron